version: '3.3'
services:
  canvas-feeby:
    container_name: canvas-feeby
    restart: unless-stopped
    image: lbjay/canvas-docker
    labels:
      caddy: canvas.lucabergman.nl
      caddy.reverse_proxy: "{{upstreams 3000}}"


networks:
  caddy:
    external: true
